name: celaya_go
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  http: ^1.1.0
  shared_preferences: ^2.2.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common: '^2.5.0+1'
  lottie: ^2.6.0
  day_night_switcher: ^0.2.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/.
  - lib/assets/.
